import type { NextPage } from 'next'
import Head from 'next/head'
import Assets from '../components/assets'
import styles from '../styles/home.module.scss'
import { useState } from 'react'

const Home: NextPage = () => {
  let [mode, setMode] = useState("dark");
  let toggleDarkMode = () => {
    console.log(mode);
    mode=="dark" ? setMode("light") : setMode("dark")
  }

  return (
    <div className={styles.container} theme-mode={mode}>
      <Head>
        <title>Assets component demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={toggleDarkMode}>DarkMode: { mode=="dark" ? 'ON' : 'OFF'}</button>
        <h1>A title in Prompt </h1>
        <Assets />
      </main>
    </div>
  )
}

export default Home
