import type { NextPage } from 'next'
import Head from 'next/head'
import Doughnut from '../components/doughnut'
import ProgressBar from '../components/progress-bar'
import Table from '../components/table'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Assets component demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Doughnut></Doughnut>
        {/* <div>
          A text <ProgressBar></ProgressBar>
        </div>
        <Table></Table> */}
      </main>
    </div>
  )
}

export default Home
