import type { NextPage } from 'next'
import Head from 'next/head'
import Assets from '../components/assets'
import styles from '../styles/home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Assets component demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>A title in Prompt </h1>
        <Assets />
      </main>
    </div>
  )
}

export default Home
